{"name": "test_add[except]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 8 == 9\n  +8\n  -9", "trace": "self = <ZhangNan01.test_jisuanqi.TestCalc object at 0x0000021E8B730CA0>\nget_calc = <test_pytest.ZhangNan01.jisuanqi.Calculator object at 0x0000021E8B6F1190>, get_datas = [3, 5, 9]\n\n    @pytest.mark.run(order=1)\n    def test_add(self,get_calc,get_datas):\n        result = None\n        try:\n        # 调用add函数,返回的结果保存在result里面\n            result = get_calc.add(get_datas[0], get_datas[1])\n        # 判断result结果是否等于期望的值\n            if isinstance(result,float):\n                result = round(result,2)\n        except Exception as e:\n            print(e)\n>       assert result == get_datas[2]\nE       assert 8 == 9\nE         +8\nE         -9\n\ntest_jisuanqi.py:20: AssertionError"}, "parameters": [{"name": "get_datas", "value": "[3, 5, 9]"}], "start": 1614180735878, "stop": 1614180735878, "uuid": "f0b5aceb-5bdc-4953-853a-5cf83d6c03e3", "historyId": "475977f85f8a67ec60b1e1f6ab6d9e8a", "testCaseId": "2e39da7c36323ec8ff48b493b1f20f5e", "fullName": "ZhangNan01.test_jisuanqi.TestCalc#test_add", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "parentSuite", "value": "ZhangNan01"}, {"name": "suite", "value": "test_jisuanqi"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-DQV1BM1"}, {"name": "thread", "value": "8460-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "ZhangNan01.test_jisuanqi"}]}